import type { ComponentCandidate, ComponentCatalogSection } from "../types/componentCatalog";

type ComponentCandidateInput = Omit<ComponentCandidate, "confidence">;

const HIGH_CONFIDENCE_COMPONENT_NAMES = new Set<string>([
  "TopAppBar",
  "PrimaryButton",
  "StepProgressHeader",
  "CookBottomNavigation",
  "CustomerBottomNavigation",
  "OrderCard",
  "SegmentedStatusTabs",
  "SearchBar",
  "CookProfileHeaderWithTrust",
  "CheckoutSectionStack",
  "OrderTrackingTimeline",
  "SubscriptionPlanCard",
]);

const withConfidence = (items: ComponentCandidateInput[]): ComponentCandidate[] => {
  return items.map((item) => ({
    ...item,
    confidence: HIGH_CONFIDENCE_COMPONENT_NAMES.has(item.name) ? "high" : "medium",
  }));
};

export const COMPONENT_CATALOG_SECTIONS: ComponentCatalogSection[] = [
  {
    id: "foundations",
    title: "Foundations",
    items: withConfidence([
      {
        id: "foundation-color-tokens",
        name: "ColorTokens",
        purpose: "Semantic palette for brand, surfaces, borders, and status colors.",
        recommendedPath: "src/constants",
        appearsIn: 8,
        variants: ["primary", "surface", "text", "status"],
      },
      {
        id: "foundation-typography-tokens",
        name: "TypographyTokens",
        purpose: "Shared type scale and text weights for all screens.",
        recommendedPath: "src/constants",
        appearsIn: 8,
        variants: ["h1", "h2", "h3", "body", "caption"],
      },
      {
        id: "foundation-spacing-radius-elevation",
        name: "SpacingRadiusElevationTokens",
        purpose: "Consistent spacing, radius, border, and shadow system.",
        recommendedPath: "src/constants",
        appearsIn: 7,
        variants: ["space-xs-xl", "radius-sm-pill", "elevation-0-3"],
      },
      {
        id: "foundation-icon-set",
        name: "IconAndEmojiSet",
        purpose: "Unified icon usage across role, status, action, and trust UI.",
        recommendedPath: "src/assets",
        appearsIn: 6,
        variants: ["outline", "filled", "status"],
      },
    ]),
  },
  {
    id: "atoms",
    title: "Atoms",
    items: withConfidence([
      {
        id: "atom-app-text",
        name: "AppText",
        purpose: "Single text primitive for typography consistency.",
        recommendedPath: "src/components/ui",
        appearsIn: 7,
        variants: ["heading", "body", "label", "caption", "link"],
      },
      {
        id: "atom-icon-button",
        name: "IconButton",
        purpose: "Reusable icon tap target for back and quick actions.",
        recommendedPath: "src/components/ui",
        appearsIn: 5,
        variants: ["ghost", "filled", "tonal"],
      },
      {
        id: "atom-primary-button",
        name: "PrimaryButton",
        purpose: "Main CTA button across onboarding and checkout flows.",
        recommendedPath: "src/components/ui",
        appearsIn: 7,
        variants: ["enabled", "disabled", "loading"],
      },
      {
        id: "atom-pill-chip",
        name: "PillChip",
        purpose: "Selectable pill for neighborhoods, radius, and filters.",
        recommendedPath: "src/components/ui",
        appearsIn: 4,
        variants: ["selected", "unselected", "softSelected"],
      },
      {
        id: "atom-badge",
        name: "Badge",
        purpose: "Small count or status indicators.",
        recommendedPath: "src/components/ui",
        appearsIn: 4,
        variants: ["count", "status", "neutral"],
      },
      {
        id: "atom-avatar",
        name: "Avatar",
        purpose: "Identity avatar for cooks, customers, and riders.",
        recommendedPath: "src/components/ui",
        appearsIn: 5,
        variants: ["image", "placeholder", "outlined"],
      },
      {
        id: "atom-divider",
        name: "Divider",
        purpose: "Section and row separator line.",
        recommendedPath: "src/components/ui",
        appearsIn: 4,
        variants: ["fullBleed", "inset", "subtle"],
      },
      {
        id: "atom-text-field",
        name: "TextField",
        purpose: "Single-line text input for profile and search.",
        recommendedPath: "src/components/ui",
        appearsIn: 5,
        variants: ["default", "focused", "error", "search"],
      },
      {
        id: "atom-textarea-field",
        name: "TextAreaField",
        purpose: "Multiline descriptive input field.",
        recommendedPath: "src/components/ui",
        appearsIn: 2,
        variants: ["default", "focused", "error"],
      },
      {
        id: "atom-switch-control",
        name: "SwitchControl",
        purpose: "Boolean toggle for accepting orders and similar settings.",
        recommendedPath: "src/components/ui",
        appearsIn: 2,
        variants: ["on", "off", "disabled"],
      },
      {
        id: "atom-progress-bar",
        name: "ProgressBar",
        purpose: "Linear progress indicator for wizard flow and capacity.",
        recommendedPath: "src/components/ui",
        appearsIn: 6,
        variants: ["determinate", "indeterminate"],
      },
    ]),
  },
  {
    id: "molecules",
    title: "Molecules",
    items: withConfidence([
      {
        id: "molecule-top-app-bar",
        name: "TopAppBar",
        purpose: "Header with back action, title, and optional subtitle/actions.",
        recommendedPath: "src/components/layout",
        appearsIn: 6,
        variants: ["titleOnly", "titleSubtitle", "withAction"],
      },
      {
        id: "molecule-step-progress-header",
        name: "StepProgressHeader",
        purpose: "Wizard step indicator with progress and step dots.",
        recommendedPath: "src/components/layout",
        appearsIn: 7,
        variants: ["step1to6", "completed", "active"],
      },
      {
        id: "molecule-otp-input-row",
        name: "OtpInputRow",
        purpose: "6-digit OTP cell row with focus and completed states.",
        recommendedPath: "src/features/auth",
        appearsIn: 3,
        variants: ["empty", "partial", "filled", "error"],
      },
      {
        id: "molecule-country-phone-input",
        name: "CountryCodePhoneInput",
        purpose: "Combined country code selector and phone input.",
        recommendedPath: "src/features/auth",
        appearsIn: 3,
        variants: ["empty", "filled", "focused"],
      },
      {
        id: "molecule-segmented-status-tabs",
        name: "SegmentedStatusTabs",
        purpose: "Status tab strip with optional counters.",
        recommendedPath: "src/features/cook",
        appearsIn: 6,
        variants: ["active", "inactive", "withCounts"],
      },
      {
        id: "molecule-search-bar",
        name: "SearchBar",
        purpose: "Search input with clear and history behavior.",
        recommendedPath: "src/components/ui",
        appearsIn: 3,
        variants: ["idle", "focused", "withRecent"],
      },
      {
        id: "molecule-stat-card",
        name: "StatCard",
        purpose: "KPI metric card for dashboard and earnings analytics.",
        recommendedPath: "src/features/cook",
        appearsIn: 5,
        variants: ["orders", "revenue", "rating", "balance"],
      },
      {
        id: "molecule-address-option-card",
        name: "AddressOptionCard",
        purpose: "Selectable address row with default state.",
        recommendedPath: "src/features/customer",
        appearsIn: 3,
        variants: ["selected", "unselected", "default"],
      },
      {
        id: "molecule-payment-method-option",
        name: "PaymentMethodOption",
        purpose: "Selectable payment method row.",
        recommendedPath: "src/features/customer",
        appearsIn: 3,
        variants: ["selected", "unselected"],
      },
      {
        id: "molecule-order-summary-row",
        name: "OrderSummaryRow",
        purpose: "Line-item row used in billing and totals summary.",
        recommendedPath: "src/components/ui",
        appearsIn: 4,
        variants: ["normal", "discount", "total"],
      },
      {
        id: "molecule-rating-input-row",
        name: "RatingInputRow",
        purpose: "Star rating control with submit action.",
        recommendedPath: "src/features/customer",
        appearsIn: 1,
        variants: ["unrated", "rated"],
      },
    ]),
  },
  {
    id: "organisms",
    title: "Organisms",
    items: withConfidence([
      {
        id: "organism-cook-bottom-nav",
        name: "CookBottomNavigation",
        purpose: "Persistent 5-tab navigation shell for cook flow.",
        recommendedPath: "src/components/layout",
        appearsIn: 6,
        variants: ["dashboard", "orders", "menu", "earnings", "profile"],
      },
      {
        id: "organism-customer-bottom-nav",
        name: "CustomerBottomNavigation",
        purpose: "Persistent 4-tab navigation shell for customer flow.",
        recommendedPath: "src/components/layout",
        appearsIn: 4,
        variants: ["home", "explore", "orders", "profile"],
      },
      {
        id: "organism-order-card",
        name: "OrderCard",
        purpose: "Flexible order card with status and action CTAs.",
        recommendedPath: "src/features/cook",
        appearsIn: 6,
        variants: ["new", "preparing", "delivery", "delivered"],
      },
      {
        id: "organism-order-tracking-timeline",
        name: "OrderTrackingTimeline",
        purpose: "Timeline view for order lifecycle tracking.",
        recommendedPath: "src/features/customer",
        appearsIn: 4,
        variants: ["inProgress", "completed"],
      },
      {
        id: "organism-document-upload-checklist",
        name: "DocumentUploadChecklist",
        purpose: "Multi-item verification upload checklist.",
        recommendedPath: "src/features/cook",
        appearsIn: 2,
        variants: ["pending", "uploaded"],
      },
      {
        id: "organism-weekly-menu-planner",
        name: "WeeklyMenuPlanner",
        purpose: "Day-based menu planning module.",
        recommendedPath: "src/features/cook",
        appearsIn: 3,
        variants: ["withDishes", "emptyDay"],
      },
      {
        id: "organism-checkout-section-stack",
        name: "CheckoutSectionStack",
        purpose: "Address, payment, promo, and billing section grouping.",
        recommendedPath: "src/features/customer",
        appearsIn: 3,
        variants: ["initial", "addressSelected", "promoApplied"],
      },
      {
        id: "organism-cook-profile-header-trust",
        name: "CookProfileHeaderWithTrust",
        purpose: "Cook profile hero with trust indicators and tab strip.",
        recommendedPath: "src/features/customer",
        appearsIn: 4,
        variants: ["menuTab", "aboutTab", "reviewsTab"],
      },
      {
        id: "organism-subscription-plan-card",
        name: "SubscriptionPlanCard",
        purpose: "Subscription plan status card with actions.",
        recommendedPath: "src/features/subscription",
        appearsIn: 4,
        variants: ["active", "paused", "upgrade"],
      },
      {
        id: "organism-notification-feed",
        name: "NotificationFeed",
        purpose: "Grouped notification list with unread indicators.",
        recommendedPath: "src/features/customer",
        appearsIn: 1,
        variants: ["today", "yesterday", "mixedUnread"],
      },
    ]),
  },
  {
    id: "templates",
    title: "Templates / Screens",
    items: withConfidence([
      {
        id: "template-role-selection",
        name: "RoleSelectionScreen",
        purpose: "Initial role choice between Customer and Home Cook.",
        recommendedPath: "src/screens",
        appearsIn: 1,
        variants: ["default"],
      },
      {
        id: "template-cook-phone-entry",
        name: "CookPhoneEntryScreen",
        purpose: "Phone entry and send-code for cook auth.",
        recommendedPath: "src/features/auth",
        appearsIn: 2,
        variants: ["empty", "filled"],
      },
      {
        id: "template-cook-otp",
        name: "CookOtpVerificationScreen",
        purpose: "OTP verification flow for cook auth.",
        recommendedPath: "src/features/auth",
        appearsIn: 2,
        variants: ["emptyOtp", "filledOtp", "verifying"],
      },
      {
        id: "template-cook-profile-setup",
        name: "CookProfileNameSetupScreen",
        purpose: "Collect profile name and optional avatar.",
        recommendedPath: "src/features/cook",
        appearsIn: 2,
        variants: ["emptyName", "filledName"],
      },
      {
        id: "template-cook-registration-wizard",
        name: "CookRegistrationWizardScreens",
        purpose: "Six-step onboarding wizard for cooks.",
        recommendedPath: "src/features/cook",
        appearsIn: 8,
        variants: ["step1", "step2", "step3", "step4", "step5", "step6"],
      },
      {
        id: "template-cook-dashboard",
        name: "CookDashboardScreen",
        purpose: "Cook home dashboard with KPIs and quick actions.",
        recommendedPath: "src/features/cook",
        appearsIn: 2,
        variants: ["acceptingOrders", "pausedOrders"],
      },
      {
        id: "template-cook-orders",
        name: "CookOrdersScreen",
        purpose: "Cook order management with status transitions.",
        recommendedPath: "src/features/cook",
        appearsIn: 6,
        variants: ["new", "preparing", "delivery", "delivered", "empty"],
      },
      {
        id: "template-cook-menu-planning",
        name: "CookMenuPlanningScreen",
        purpose: "Weekly menu planner by weekday.",
        recommendedPath: "src/features/cook",
        appearsIn: 3,
        variants: ["withDishes", "empty"],
      },
      {
        id: "template-cook-earnings",
        name: "CookEarningsScreen",
        purpose: "Balance, history, and withdraw experience.",
        recommendedPath: "src/features/cook",
        appearsIn: 3,
        variants: ["overview", "transactions"],
      },
      {
        id: "template-cook-profile-settings",
        name: "CookProfileSettingsScreen",
        purpose: "Profile details and settings list for cook account.",
        recommendedPath: "src/features/cook",
        appearsIn: 3,
        variants: ["verificationPending", "settingsList"],
      },
      {
        id: "template-customer-auth",
        name: "CustomerAuthScreens",
        purpose: "Customer OTP and profile setup flow.",
        recommendedPath: "src/features/customer",
        appearsIn: 2,
        variants: ["otp", "profileSetup"],
      },
      {
        id: "template-customer-discovery",
        name: "CustomerDiscoveryScreens",
        purpose: "Home, search, and explore journey for customer.",
        recommendedPath: "src/features/customer",
        appearsIn: 4,
        variants: ["home", "searchHistory", "filtered"],
      },
      {
        id: "template-cook-profile-detail",
        name: "CookProfileDetailScreens",
        purpose: "Cook detail tabs: menu, about, reviews.",
        recommendedPath: "src/features/customer",
        appearsIn: 4,
        variants: ["menu", "about", "reviews"],
      },
      {
        id: "template-cart-checkout",
        name: "CartAndCheckoutScreens",
        purpose: "Cart summary and checkout forms.",
        recommendedPath: "src/features/customer",
        appearsIn: 4,
        variants: ["cart", "checkout", "billingFocused"],
      },
      {
        id: "template-order-lifecycle",
        name: "OrderLifecycleScreens",
        purpose: "Placed, tracking, delivered, history, and rating.",
        recommendedPath: "src/features/customer",
        appearsIn: 5,
        variants: ["placed", "tracking", "delivered", "history"],
      },
      {
        id: "template-customer-profile-subscription",
        name: "CustomerProfileAndSubscriptionScreens",
        purpose: "Customer profile and subscription management views.",
        recommendedPath: "src/features/subscription",
        appearsIn: 5,
        variants: ["profile", "subscriptionActive"],
      },
      {
        id: "template-notifications",
        name: "NotificationsScreen",
        purpose: "Notification feed grouped by date and unread state.",
        recommendedPath: "src/features/customer",
        appearsIn: 1,
        variants: ["unreadMixed"],
      },
    ]),
  },
];
